# Generated by Django 5.0 on 2026-04-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=255)),
                ('clientName', models.CharField(max_length=255)),
                ('clientEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('clientPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('photographerId', models.CharField(max_length=255)),
                ('photographerName', models.CharField(max_length=255)),
                ('photographerImage', models.TextField(blank=True, null=True)),
                ('photographerCity', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('eventType', models.CharField(blank=True, max_length=255, null=True)),
                ('locationDetails', models.TextField(blank=True, null=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='upcoming', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('reviews', models.IntegerField(default=0)),
                ('specialty', models.CharField(max_length=255)),
                ('whyChosen', models.TextField()),
                ('mapQuery', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('instaUrl', models.TextField(blank=True, null=True)),
                ('portfolio', models.JSONField(default=list)),
            ],
        ),
    ]
